name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'      # если в build.gradle toolchain=24
          distribution: 'temurin' # adopt устарел → temurin
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (tests включены)
        run: ./gradlew clean build --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jars
          if-no-files-found: error
          path: |
            build/libs/*.jar
